[build]
  # This is the directory to deploy
  publish = "dist"
  
  # This is the command that will be run to build your site
  command = """
    npm install
    npm run build
  """

# Set environment variables
[build.environment]
  NODE_VERSION = "18"
  
# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
